modLoader = "javafml"
loaderVersion = "[${forge_version},)"
issueTrackerURL = "https://github.com/Wagers-of-Industrial-Warfare/RitchiesProjectileLib/issues"
license = "MIT License"

[[mods]]
modId = "ritchiesprojectilelib"
version = "${version}"
displayName = "Ritchie's Projectile Library"
authors = "rbasamoyai"
description = '''A Minecraft modding library for better projectiles.'''
logoFile = "icon.png"

[[dependencies.ritchiesprojectilelib]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ritchiesprojectilelib]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"