org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.caching=true

# Mod Info
mod.id=ritchiesprojectilelib
mod.group=com.rbasamoyai
mod.version=2.1.2

deps.mixin_extras=0.4.1

deps.forge_loader=[VERSIONED]
deps.fabric_loader=[VERSIONED]
deps.fabric_api_version=[VERSIONED]

deps.config_api_version=[VERSIONED]

deps.porting_lib_modules=networking,utility,base

